- name: compressed-size-action
  # You may pin to the exact commit or the version.
  # uses: preactjs/compressed-size-action@e2bfc4b346d78f9a3c7e8a2e22bcbd285a25fafa
  uses: preactjs/compressed-size-action@v2
  with:
    # The GITHUB_TOKEN secret
    repo-token: 
    # The npm-script to run that builds your project
    build-script: # optional, default is build
    # The compression algorithm to use: "gzip" or "brotli"
    compression: # optional
    # Show total size and difference.
    show-total: # optional, default is true
    # Move unchanged files into a separate collapsed table
    collapse-unchanged: # optional, default is true
    # Exclude unchanged files from the sizes table entirely
    omit-unchanged: # optional
    # A regular expression to remove hashes from filenames. Submatches are turned into asterisks if present, otherwise the whole match is removed.
    strip-hash: # optional
    # Report status as a CI Check instead of using a comment [experimental]
    use-check: # optional
    # Consider files with changes below this threshold as unchanged. Specified in bytes.
    minimum-change-threshold: # optional, default is 1
    # minimatch pattern of files to track
    pattern: # optional, default is **/dist/**/*.js
    # minimatch pattern of files NOT to track
    exclude: # optional, default is {**/*.map,**/node_modules/**}
